### PR TITLE
make HYPRE 2.11.2 compile with Visual Studio

### PR DESCRIPTION
**Pull request by janusw**
* tested with VS2005
* some C files were supposed to be compiled as C++, which was not working
* this fixes it by setting the right file property (LANGUAGE instead of COMPILE_FLAGS)

### CODE REVIEW

**Comment by janusw** [comment]
for discussion, see issue #12

**Comment by rfalgout** [comment]
Hi Janus,

Thanks for looking into this problem.  I will be out of the country for a bit, but will take a look at this when I return.  Thanks again!

-Rob

**Comment by janusw** [comment]
This pull request is somewhat outdated by now. I fixed all problems I found with VS 2005 & 2015 (including the one mentioned above) on my branch https://github.com/janusw/hypre/tree/v2.12.0-vs

(cf. issues #12, #14, #16, #17)

Are there chances you might want to merge any of this into your main repo?

Related questions:
* Is version 2.12.0 officially released by now? (I only see the corresponding tag on github, but no mention of it on your website yet.)
* Will there be another release in the 2.11.x series?

Cheers,
Janus

**Comment by rfalgout** [comment]
Hi Janus,

I'd like to thank you for all the effort you put into porting to the different VS versions!  We do intend to use what you learned to update the code.  We just got a server that we will use for Windows testing.  Once it is up and running, we'll either merge your changes in directly or make a few mods to them.  Our actual development repo is not on Github, so we'll replicate your pull request over here first.

There will be no new 2.11.x releases.  We have not advertised 2.12 because there are some major GPU-related updates that we want "friendly users" to try out first.  Your changes will probably be on a new 2.12.x release.

Thanks again!

-Rob

**Comment by janusw** [comment]
Thanks for the feedback, Rob. I'm looking forward to your next release.

As mentioned earlier, I think it would also help if you could add a bit of documentation about which systems/compilers are supported by HYPRE and can be expected to work.

Thanks,
Janus

**Comment by rfalgout** [comment]
Closing this pull request.  VS now works with hypre 2.13.0.

**Pull request closed without merging**
